import { NextResponse } from 'next/server';

const PROVINCES = [
  {
    id: 1,
    code: 'DN',
    name: 'Dong Nai',
    region: 'Southeast',
    total_plots: 85,
    total_area_ha: 5894.5,
    center_lat: 11.10,
    center_lng: 107.22,
  },
  {
    id: 2,
    code: 'BP',
    name: 'Binh Phuoc',
    region: 'Southeast',
    total_plots: 62,
    total_area_ha: 6892.1,
    center_lat: 11.75,
    center_lng: 106.85,
  },
  {
    id: 3,
    code: 'LD',
    name: 'Lam Dong',
    region: 'Central Highlands',
    total_plots: 98,
    total_area_ha: 9780.3,
    center_lat: 11.94,
    center_lng: 108.44,
  },
  {
    id: 4,
    code: 'DNO',
    name: 'Dak Nong',
    region: 'Central Highlands',
    total_plots: 45,
    total_area_ha: 6510.7,
    center_lat: 12.23,
    center_lng: 107.60,
  },
  {
    id: 5,
    code: 'BT',
    name: 'Binh Thuan',
    region: 'Southeast',
    total_plots: 38,
    total_area_ha: 7845.2,
    center_lat: 11.09,
    center_lng: 108.47,
  },
  {
    id: 6,
    code: 'BRVT',
    name: 'Ba Ria-Vung Tau',
    region: 'Southeast',
    total_plots: 29,
    total_area_ha: 1989.5,
    center_lat: 10.64,
    center_lng: 107.28,
  },
  {
    id: 7,
    code: 'TN',
    name: 'Tay Ninh',
    region: 'Southeast',
    total_plots: 41,
    total_area_ha: 4028.3,
    center_lat: 11.33,
    center_lng: 106.10,
  },
  {
    id: 8,
    code: 'BD',
    name: 'Binh Duong',
    region: 'Southeast',
    total_plots: 22,
    total_area_ha: 2693.8,
    center_lat: 11.16,
    center_lng: 106.65,
  },
  {
    id: 9,
    code: 'HCM',
    name: 'Ho Chi Minh',
    region: 'Southeast',
    total_plots: 15,
    total_area_ha: 2095.4,
    center_lat: 10.82,
    center_lng: 106.63,
  },
  {
    id: 10,
    code: 'LA',
    name: 'Long An',
    region: 'Mekong Delta',
    total_plots: 33,
    total_area_ha: 4491.6,
    center_lat: 10.69,
    center_lng: 106.19,
  },
];

export async function GET() {
  return NextResponse.json({
    data: PROVINCES,
    meta: {
      total: PROVINCES.length,
      regions: ['Southeast', 'Central Highlands', 'Mekong Delta'],
    },
  });
}
